apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: incident-mysql-pvc
  labels:
    app: incident-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi