openapi: 3.0.0
info:
  title: API Incidents Jurassic Park
  version: 1.0.0
  description: API REST pour la gestion des incidents du parc

servers:
  - url: http://localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Incident:
      type: object
      properties:
        id:
          type: integer
          example: 1
        titre:
          type: string
          example: Fuite de T-Rex
        description:
          type: string
          example: Le T-Rex a cassé la clôture.
        type:
          type: string
          example: Evasion
        zone:
          type: string
          example: T-Rex Valley
        urgence:
          type: string
          example: Haute
        statut:
          type: string
          example: En cours

security:
  - bearerAuth: []

paths:
  /incidents:
    get:
      summary: Liste tous les incidents
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Liste des incidents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Incident'
    post:
      summary: Crée un nouvel incident
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Incident'
      responses:
        '201':
          description: Incident créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Incident'
        '400':
          description: Erreur de validation

  /incidents/{id}:
    put:
      summary: Met à jour un incident
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Incident'
      responses:
        '200':
          description: Incident mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Incident'
        '404':
          description: Incident non trouvé
    delete:
      summary: Supprime un incident
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Incident supprimé
        '404':
          description: Incident non trouvé